DELIMITER $$
DROP PROCEDURE IF EXISTS `ORDER_LAST_ID` $$
CREATE PROCEDURE `ORDER_LAST_ID`(OUT lastId BIGINT)
BEGIN
    SET lastID = (SELECT `AUTO_INCREMENT`
                  FROM  INFORMATION_SCHEMA.TABLES
                  WHERE TABLE_SCHEMA = 'tecnovision'
                    AND TABLE_NAME = 'orders');
END$$
DELIMITER ;